# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbase.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\t\"\x1e\n\x0bOCRResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x91\x01\n\x03OCR\x12\x35\n\x14\x64\x65tect_and_recognize\x12\r.ImageRequest\x1a\x0c.OCRResponse\"\x00\x12\'\n\x06\x64\x65tect\x12\r.ImageRequest\x1a\x0c.OCRResponse\"\x00\x12*\n\trecognize\x12\r.ImageRequest\x1a\x0c.OCRResponse\"\x00\x62\x06proto3')
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ImageRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=43,
)


_OCRRESPONSE = _descriptor.Descriptor(
  name='OCRResponse',
  full_name='OCRResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='OCRResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['OCRResponse'] = _OCRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEREQUEST,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:ImageRequest)
  ))
_sym_db.RegisterMessage(ImageRequest)

OCRResponse = _reflection.GeneratedProtocolMessageType('OCRResponse', (_message.Message,), dict(
  DESCRIPTOR = _OCRRESPONSE,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:OCRResponse)
  ))
_sym_db.RegisterMessage(OCRResponse)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect_and_recognize',
    full_name='OCR.detect_and_recognize',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_OCRRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='detect',
    full_name='OCR.detect',
    index=1,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_OCRRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recognize',
    full_name='OCR.recognize',
    index=2,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_OCRRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR

# @@protoc_insertion_point(module_scope)
